/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddReviewInput {
  'title' : string,
  'isbn' : [] | [string],
  'cover' : [] | [ExternalBlob],
  'reviewText' : string,
  'author' : string,
  'rating' : bigint,
}
export interface Comment {
  'id' : bigint,
  'createdAt' : Time,
  'user' : string,
  'reviewId' : ReviewId,
  'commentText' : string,
}
export type ExternalBlob = Uint8Array;
export interface Progress { 'status' : string, 'percentage' : bigint }
export type Rating = bigint;
export interface ReadingMetrics {
  'totalHours' : bigint,
  'sessions' : Array<ReadingSession>,
  'totalBooks' : bigint,
  'totalPages' : bigint,
}
export interface ReadingSession {
  'startTime' : Time,
  'endTime' : [] | [Time],
  'bookId' : bigint,
  'pagesRead' : bigint,
}
export interface Review {
  'id' : ReviewId,
  'title' : string,
  'isbn' : [] | [string],
  'createdAt' : Time,
  'cover' : [] | [ExternalBlob],
  'reviewText' : string,
  'likedBy' : Array<Principal>,
  'author' : string,
  'likes' : bigint,
  'rating' : Rating,
}
export type ReviewId = bigint;
export type Time = bigint;
export interface TrackedBook {
  'id' : bigint,
  'title' : string,
  'isbn' : [] | [string],
  'author' : string,
  'progress' : Progress,
}
export interface UserProfile { 'name' : string, 'avatar' : [] | [ExternalBlob] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[ReviewId, string, string], bigint>,
  'addReview' : ActorMethod<
    [string, string, [] | [string], Rating, string],
    ReviewId
  >,
  'addReviewWithCover' : ActorMethod<[AddReviewInput], ReviewId>,
  'addTrackedBook' : ActorMethod<[string, string, [] | [string]], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'finishBook' : ActorMethod<[], undefined>,
  'finishReadingSession' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[ReviewId], Array<Comment>>,
  'getGlobalReadingMetrics' : ActorMethod<
    [],
    { 'totalHours' : bigint, 'totalBooks' : bigint, 'totalPages' : bigint }
  >,
  'getLatestReviews' : ActorMethod<[bigint], Array<Review>>,
  'getReadingMetrics' : ActorMethod<[], [] | [ReadingMetrics]>,
  'getReview' : ActorMethod<[ReviewId], [] | [Review]>,
  'getTrackedBooks' : ActorMethod<[], Array<TrackedBook>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeReview' : ActorMethod<[ReviewId], undefined>,
  'removeTrackedBook' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startReadingSession' : ActorMethod<[bigint], undefined>,
  'unlikeReview' : ActorMethod<[ReviewId], undefined>,
  'updateBookProgress' : ActorMethod<[bigint, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];