/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ReviewId = IDL.Nat;
export const Rating = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AddReviewInput = IDL.Record({
  'title' : IDL.Text,
  'isbn' : IDL.Opt(IDL.Text),
  'cover' : IDL.Opt(ExternalBlob),
  'reviewText' : IDL.Text,
  'author' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'user' : IDL.Text,
  'reviewId' : ReviewId,
  'commentText' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'title' : IDL.Text,
  'isbn' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'cover' : IDL.Opt(ExternalBlob),
  'reviewText' : IDL.Text,
  'likedBy' : IDL.Vec(IDL.Principal),
  'author' : IDL.Text,
  'likes' : IDL.Nat,
  'rating' : Rating,
});
export const ReadingSession = IDL.Record({
  'startTime' : Time,
  'endTime' : IDL.Opt(Time),
  'bookId' : IDL.Nat,
  'pagesRead' : IDL.Nat,
});
export const ReadingMetrics = IDL.Record({
  'totalHours' : IDL.Nat,
  'sessions' : IDL.Vec(ReadingSession),
  'totalBooks' : IDL.Nat,
  'totalPages' : IDL.Nat,
});
export const Progress = IDL.Record({
  'status' : IDL.Text,
  'percentage' : IDL.Nat,
});
export const TrackedBook = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isbn' : IDL.Opt(IDL.Text),
  'author' : IDL.Text,
  'progress' : Progress,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([ReviewId, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), Rating, IDL.Text],
      [ReviewId],
      [],
    ),
  'addReviewWithCover' : IDL.Func([AddReviewInput], [ReviewId], []),
  'addTrackedBook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'finishBook' : IDL.Func([], [], []),
  'finishReadingSession' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([ReviewId], [IDL.Vec(Comment)], ['query']),
  'getGlobalReadingMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalHours' : IDL.Nat,
          'totalBooks' : IDL.Nat,
          'totalPages' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLatestReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getReadingMetrics' : IDL.Func([], [IDL.Opt(ReadingMetrics)], ['query']),
  'getReview' : IDL.Func([ReviewId], [IDL.Opt(Review)], ['query']),
  'getTrackedBooks' : IDL.Func([], [IDL.Vec(TrackedBook)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeReview' : IDL.Func([ReviewId], [], []),
  'removeTrackedBook' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startReadingSession' : IDL.Func([IDL.Nat], [], []),
  'unlikeReview' : IDL.Func([ReviewId], [], []),
  'updateBookProgress' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ReviewId = IDL.Nat;
  const Rating = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AddReviewInput = IDL.Record({
    'title' : IDL.Text,
    'isbn' : IDL.Opt(IDL.Text),
    'cover' : IDL.Opt(ExternalBlob),
    'reviewText' : IDL.Text,
    'author' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'user' : IDL.Text,
    'reviewId' : ReviewId,
    'commentText' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'title' : IDL.Text,
    'isbn' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'cover' : IDL.Opt(ExternalBlob),
    'reviewText' : IDL.Text,
    'likedBy' : IDL.Vec(IDL.Principal),
    'author' : IDL.Text,
    'likes' : IDL.Nat,
    'rating' : Rating,
  });
  const ReadingSession = IDL.Record({
    'startTime' : Time,
    'endTime' : IDL.Opt(Time),
    'bookId' : IDL.Nat,
    'pagesRead' : IDL.Nat,
  });
  const ReadingMetrics = IDL.Record({
    'totalHours' : IDL.Nat,
    'sessions' : IDL.Vec(ReadingSession),
    'totalBooks' : IDL.Nat,
    'totalPages' : IDL.Nat,
  });
  const Progress = IDL.Record({ 'status' : IDL.Text, 'percentage' : IDL.Nat });
  const TrackedBook = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isbn' : IDL.Opt(IDL.Text),
    'author' : IDL.Text,
    'progress' : Progress,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([ReviewId, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), Rating, IDL.Text],
        [ReviewId],
        [],
      ),
    'addReviewWithCover' : IDL.Func([AddReviewInput], [ReviewId], []),
    'addTrackedBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'finishBook' : IDL.Func([], [], []),
    'finishReadingSession' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([ReviewId], [IDL.Vec(Comment)], ['query']),
    'getGlobalReadingMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalHours' : IDL.Nat,
            'totalBooks' : IDL.Nat,
            'totalPages' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLatestReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getReadingMetrics' : IDL.Func([], [IDL.Opt(ReadingMetrics)], ['query']),
    'getReview' : IDL.Func([ReviewId], [IDL.Opt(Review)], ['query']),
    'getTrackedBooks' : IDL.Func([], [IDL.Vec(TrackedBook)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeReview' : IDL.Func([ReviewId], [], []),
    'removeTrackedBook' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startReadingSession' : IDL.Func([IDL.Nat], [], []),
    'unlikeReview' : IDL.Func([ReviewId], [], []),
    'updateBookProgress' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };